INSERT INTO Restaurants (name, address, plus_code) VALUES
('Toit Brewpub', '298, Namma Metro Pillar 62, 100 Feet Road, Indiranagar, Bangalore', 'XH4V+M5 Bangalore, Karnataka'),
('The Black Rabbit', '770, Escape Hotel, 100 Feet Road, Indiranagar, Bangalore', 'XH4W+7X Bangalore, Karnataka'),
('The Fatty Bao', '610, 3rd Floor, 12th Main Road, HAL 2nd Stage, Indiranagar, Bangalore', 'XH4V+56 Bangalore, Karnataka'),
('MTR 1924', '14, Lalbagh Road, Near Lalbagh Main Gate, Bangalore', 'WHX3+3X Bangalore, Karnataka'),
('Koshys', '39, St. Marks Road, Shanthala Nagar, Ashok Nagar, Bangalore', 'XH2C+3Q Bangalore, Karnataka'),
('Arbor Brewing Company', '8, Magrath Road, Brigade Road, Bangalore', 'XH2J+4C Bangalore, Karnataka'),
('Corner House', '14, Residency Road, Bangalore', 'XH2H+9G Bangalore, Karnataka'),
('Airlines Hotel', 'No.4, Madras Bank Road, Off Lavelle Road, Bangalore', 'XH2H+7J Bangalore, Karnataka'),
('Vidyaarthi Bhavan', '32, Gandhi Bazaar, Near Gandhi Bazaar Circle, Basavanagudi, Bangalore', 'WHX8+99 Bangalore, Karnataka'),
('Truffles', '93/A, Aurobindo Marg, 4th Block, Koramangala, Bangalore', 'XH3W+QP Bangalore, Karnataka'),
('Brahmins Coffee Bar', '3, Ranga Rao Road, Shankarapura, Bangalore', 'WHW8+5V Bangalore, Karnataka'),
('Sri Sagar (CTR)', '7th Cross, Margosa Road, Malleshwaram, Bangalore', 'WHX5+XQ Bangalore, Karnataka'),
('Nagarjuna', '44/1, Residency Road, Shanthala Nagar, Ashok Nagar, Bangalore', 'XH2J+2H Bangalore, Karnataka'),
('Meghana Foods', '52, 1st Main Road, Near NMH Complex, Koramangala 2nd Block, Bangalore', 'XH3R+HR Bangalore, Karnataka'),
('Shivaji Military Hotel', '718, 1st C Main Road, 8th Block, Jayanagar, Bangalore', 'WHX2+7P Bangalore, Karnataka'),
('Karavalli', '66, Residency Road, Bangalore', 'XH2J+87 Bangalore, Karnataka'),
('Chinita Real Mexican Food', '12th Main Road, HAL 2nd Stage, Indiranagar, Bangalore', 'XH4W+3X Bangalore, Karnataka'),
('Church Street Social', '46/1, Cobalt Building, Church Street, Bangalore', 'XH2G+8R Bangalore, Karnataka'),
('Sunnys', '50, Lavelle Road, Bangalore', 'XH2J+5M Bangalore, Karnataka'),
('Little Italy', 'Indiranagar, 100 Feet Road, Bangalore', 'XH4V+9X Bangalore, Karnataka'),
('Rim Naam', 'The Oberoi, MG Road, Bangalore', 'XH2J+27 Bangalore, Karnataka'),
('Edo Japanese Restaurant and Bar', 'ITC Gardenia, 1, Residency Road, Bangalore', 'XH2J+3M Bangalore, Karnataka'),
('Mikusu', 'Conrad Bengaluru, Kensington Road, Ulsoor, Bangalore', 'XH2H+9M Bangalore, Karnataka'),
('Persian Terrace', 'Sheraton Grand Bangalore, Brigade Gateway, Bangalore', 'WHX3+7V Bangalore, Karnataka'),
('SodaBottleOpenerWala', '105, 1st Floor, Lavelle Road, Bangalore', 'XH2J+8H Bangalore, Karnataka'),
('Rajdhani Thali Restaurant', '2nd Floor, Garuda Mall, Magrath Road, Bangalore', 'XH2J+4H Bangalore, Karnataka'),
('The Humming Tree', '949, 12th Main Road, HAL 2nd Stage, Indiranagar, Bangalore', 'XH4W+45 Bangalore, Karnataka'),
('JW Kitchen', 'JW Marriott, 24/1, Vittal Mallya Road, Bangalore', 'XH2J+9C Bangalore, Karnataka'),
('Karama Restaurant', '167, 1st Floor, Brigade Road, Bangalore', 'XH2G+7R Bangalore, Karnataka'),
('Italia', 'The Park Bangalore, MG Road, Bangalore', 'XH2J+9R Bangalore, Karnataka'),
('The Biere Club', '20/2, Vittal Mallya Road, Bangalore', 'XH2J+9J Bangalore, Karnataka'),
('Jalsa Gold', '26/1, Outer Ring Road, Marathahalli, Bangalore', 'XH4R+XJ Bangalore, Karnataka'),
('Sattvam', 'No. 3/4, Sankey Road, High Grounds, Bangalore', 'XH2J+4C Bangalore, Karnataka'),
('Dum Pukht Jolly Nabobs', 'ITC Windsor, 25, Golf Course Road, Bangalore', 'XH2J+3V Bangalore, Karnataka'),
('Tandoor', '28, MG Road, Bangalore', 'XH2J+27 Bangalore, Karnataka'),
('Byg Brewski Brewing Company', '22, Hennur Bagalur Road, Near Kannuru, Bangalore', 'XH4V+7H Bangalore, Karnataka'),
('Ebony', '13th Floor, Barton Centre, MG Road, Bangalore', 'XH2J+8H Bangalore, Karnataka'),
('The 13th Floor', '84, 13th Floor, Barton Centre, MG Road, Bangalore', 'XH2J+9H Bangalore, Karnataka'),
('Oota', '618, 12th Main Road, HAL 2nd Stage, Indiranagar, Bangalore', 'XH4W+4C Bangalore, Karnataka'),
('Vidyarthi Bhavan', '32, Gandhi Bazaar Main Road, Basavanagudi, Bangalore', 'WHX8+99 Bangalore, Karnataka'),
('Alto Vino', 'Whitefield Main Road, Bangalore', 'XH4R+7R Bangalore, Karnataka'),
('Paranda', 'Taj Yeshwantpur, 2275, Tumkur Road, Bangalore', 'XH4R+7M Bangalore, Karnataka'),
('Peshawri', 'ITC Windsor, Golf Course Road, Bangalore', 'XH2J+5V Bangalore, Karnataka'),
('Masala Klub', 'Taj West End, Race Course Road, Bangalore', 'XH2J+4G Bangalore, Karnataka'),
('Lapis', 'The Oberoi, MG Road, Bangalore', 'XH2J+29 Bangalore, Karnataka'),
('MTR', '14, Lalbagh Road, Near Basavanagudi, Bangalore', 'WHX3+3X Bangalore, Karnataka'),
('New Krishna Bhavan', '33, Sampige Road, Malleshwaram, Bangalore', 'WHX6+G3 Bangalore, Karnataka'),
('Sankalp', '22, 2nd Floor, Commercial Street, Bangalore', 'XH2J+7J Bangalore, Karnataka'),
('Sattvam', '315, 100 Feet Road, Indiranagar, Bangalore', 'XH4V+5R Bangalore, Karnataka'),
('Udupi Krishna Bhavan', '112, 2nd Main, 6th Cross, Gandhi Bazaar, Bangalore', 'WHX8+6M Bangalore, Karnataka'),
('Cubbon Pavilion', 'ITC Gardenia, Residency Road, Bangalore', 'XH2J+3G Bangalore, Karnataka'),
('Hakuna Matata','1231/35/2, Brigade Millenium Rd, opposite Brigade Palmsprings, Paradise Colony, JP Nagar 7th Phase, J. P. Nagar, Bengaluru, Karnataka 560078','VHVP+HJ Bengaluru, Karnataka'),
('Thalassery restaurant','1763, 14th Main Rd, 1st Stage, Kumaraswamy Layout, Bengaluru, Karnataka 560078','WH47+WH Bengaluru, Karnataka'),
('Udupi Swada','No.587, Ground and1st Floor, 14th Main Road, 20th Cross Rd, 1st Stage, Kumaraswamy Layout, Bengaluru, Karnataka 560078','WH57+2J Bengaluru, Karnataka'),
('Dwaraka Grand','Dayanand Sagar College Rd, Kumaraswamy Layout, Bengaluru, Karnataka 560078','WH58+V6 Bengaluru, Karnataka');
